Gallery/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin

from . import views

app_name = 'Gallery'
urlpatterns = [
    url(r'events/$', views.EventList.as_view()),
    path('event/<int:id>/', views.GalleryByEventList.as_view()),
    path('client/<int:id>/', views.GalleryByClientList.as_view()),
    path('email/', views.GalleriesFromEmail.as_view()),

    path('picture/<int:pk>/', views.PictureDetails.as_view()),
    path('pictures/cart/', views.AddPrintsToCart, name='AddPrintsToCart'),

    path('<int:id>/', views.PictureByGalleryList.as_view()),
]

Site/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib import admin

from .views import Home, PriceTable, About, Sessions, Cart


app_name = "Site"
urlpatterns = [
    path('', Home.as_view()),
    path('prints/', PriceTable.as_view()),
    path('about/', About.as_view()),
    path('session-info/', Sessions.as_view()),
    path('cart/', Cart.as_view(), name="Cart")
]

Skode/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin


urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('gallery/', include('Gallery.urls', namespace="Gallery")),
    path('', include('Site.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Gallery/models.py
from django.db import models
from sorl.thumbnail import ImageField


class Event(models.Model):
    name = models.CharField(max_length=200)
    date = models.DateField()

    featured = models.ForeignKey('Picture', blank=True, null=True, on_delete=models.SET_NULL, related_name="featured_set")
    
    def __str__(self):
        return "%s (%s)" % (self.name, self.date)


class Client(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(blank=True, null=True)
    
    def __str__(self):
        return "%s <%s>" % (self.name, self.email)


class PricePoint(models.Model):
    name = models.CharField(max_length=200)
    print_type = models.CharField(max_length=200)
    print_size = models.CharField(max_length=200)

    price = models.FloatField()

    @property
    def formatted_price(self):
        return "${:.2f}".format(self.price)

    def __str__(self):
        return self.name


class Gallery(models.Model):
    name = models.CharField(max_length=200)
    client = models.ForeignKey(
        Client,
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    event = models.ForeignKey(
        Event,
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    unlisted = models.BooleanField(default=False)
    price_points = models.ManyToManyField(PricePoint, blank=True)

    def __str__(self):
        return self.name


class Picture(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE)
    image = ImageField(upload_to="doggos")

    def __str__(self):
        return self.image.name

Site/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType


class CarouselItem(models.Model):
    image = models.ImageField(upload_to="carousel")
    alt = models.CharField(max_length=200, blank=True, null=True)
    caption = models.CharField(max_length=200, blank=True, null=True)
    button_label = models.CharField(max_length=200, blank=True, null=True)
    button_url = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.image.name


class Order(models.Model):
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )
    total = models.FloatField()

    def __str__(self):
        return f'Order #{self.pk}: ${self.total}'


class CartItem(models.Model):
    item_content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, related_name="cart_item_item")
    item_object_id = models.PositiveIntegerField()
    item_content_object = GenericForeignKey('item_content_type', 'item_object_id')

    category_content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, related_name="cart_item_category")
    category_object_id = models.PositiveIntegerField()
    category_content_object = GenericForeignKey('category_content_type', 'category_object_id')

    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )

    price = models.FloatField()
    taxable = models.BooleanField(default=True)
    status = models.CharField(
        max_length=1,
        default='A',
        choices=(
            ('A', 'Active'),
            ('S', 'Sold')
        )
    )
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        blank=True, null=True
    )

    @property
    def tax(self):
        if self.taxable:
            return self.price * settings.TAX_RATE
        else:
            return 0

    @property
    def total(self):
        return self.price + self.tax

    def __str__(self):
        return f'Cart item {self.category_content_object} in {self.user}\'s cart'

Gallery/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import ListView, DetailView

from .models import Client, Event, Picture, Gallery, PricePoint
from Site.models import CartItem


class EventList(ListView):
    model = Event
    ordering = "-date"


class GalleryByEventList(ListView):
    model = Gallery
    template_name = "Gallery/galleries_by_event_list.html"

    def get_queryset(self, **kwargs):
        return Gallery.objects.filter(event=self.kwargs['id'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['event'] = Event.objects.get(pk=self.kwargs['id'])
        return context


class GalleryByClientList(ListView):
    model = Gallery
    template_name = "Gallery/galleries_by_client_list.html"

    def get_queryset(self, **kwargs):
        return Gallery.objects.filter(client=self.kwargs['id'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['client'] = Client.objects.get(pk=self.kwargs['id'])
        return context


class GalleriesFromEmail(ListView):
    model = Gallery
    template_name = "Gallery/galleries_by_client_list.html"

    def get_queryset(self, **kwargs):
        return Gallery.objects.filter(
            client__email=self.request.GET.get('email', '')
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['client'] = Client.objects.get(
            email=self.request.GET.get('email', '')
        )
        return context


class PictureByGalleryList(ListView):
    model = Picture
    template_name = "Gallery/pictures_by_gallery_list.html"

    def get_queryset(self, **kwargs):
        return Picture.objects.filter(gallery=self.kwargs['id'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['gallery'] = Gallery.objects.get(pk=self.kwargs['id'])
        return context


class PictureDetails(DetailView):
    model = Picture


def AddPrintsToCart(request):
    prints = request.POST.getlist('PriceOptions')
    pictures = request.POST.getlist('Pictures')

    for picturePK in pictures:
        picture = Picture.objects.get(pk=picturePK)
        for itemPK in prints:
            price = PricePoint.objects.get(pk=itemPK)
            CartItem.objects.create(
                content_object=picture,
                user=request.user,
                price=price.price
            )

    return redirect('Site:Cart')

Site/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView

from .models import CarouselItem, CartItem, Order
from Gallery.models import PricePoint


class Home(TemplateView):
    template_name = "Site/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['carousel'] = CarouselItem.objects.all()
        return context


class About(TemplateView):
    template_name = "Site/about.html"


class Sessions(TemplateView):
    template_name = "Site/sessions.html"


class PriceTable(ListView):
    model = PricePoint
    template_name = "Site/price.html"


class Cart(ListView):
    model = CartItem
    template_name = "Site/cart.html"

Gallery/templates/Gallery/event_list.html
{% extends 'base.html' %}

{% block extra_head %}
    {{ block.super }}
{% endblock extra_head %}

{% block container %}
    <h3 style="margin-top: 15px">Event List</h3>
    <div class="row">
        {% for item in object_list %}
            <div class="col-12 col-md-6 col-lg-4 col-xl-3" onclick="window.location = '#'">
                <div class="gallery-list-item" style="background-image:url('/media/{{ item.featured.image }}');">
                    <div class="gallery-list-caption">{{ item.name|upper }}</div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock container %}
    

Gallery/templates/Gallery/galleries_by_client_list.html
{% extends 'base.html' %}

{% block extra_head %}
    {{ block.super }}
{% endblock extra_head %}

{% block container %}
    <h3 style="margin-top: 15px">{{ client.name }} Galleries</h3>
    <div class="row">
        {% for item in object_list %}
            <div class="col-12 col-md-6 col-lg-4 col-xl-3" onclick="window.location = '/gallery/{{ item.id }}'">
                <div class="gallery-list-item" style="background-image:url('/media/{{ item.picture_set.first.image }}');">
                    <div class="gallery-list-caption">{{ item.name|upper }}</div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock container %}
    

Gallery/templates/Gallery/galleries_by_event_list.html
{% extends 'base.html' %}

{% block extra_head %}
    {{ block.super }}
{% endblock extra_head %}

{% block container %}
    <h3 style="margin-top: 15px">{{ event.name }} Galleries</h3>
    <div class="row">
        {% for item in object_list %}
            <div class="col-12 col-md-6 col-lg-4 col-xl-3" onclick="window.location = '/gallery/{{ item.id }}'">
                <div class="gallery-list-item" style="background-image:url('/media/{{ item.picture_set.first.image }}');">
                    <div class="gallery-list-caption">{{ item.name|upper }}</div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock container %}
    

Gallery/templates/Gallery/picture_detail.html
{% extends 'base.html' %}
{% load thumbnail %}


{% block container %}
    <div class="breadcrumbs">
        / Event: <a href="/gallery/event/{{ object.gallery.event.pk }}">{{ object.gallery.event.name }}</a> / 
        Client: <a href="/gallery/client/{{ object.gallery.client.pk }}">{{ object.gallery.client.name }}</a> /
        Gallery: <a href="/gallery/{{ object.gallery.pk }}">{{ object.gallery.name }}</a> /
    </div>
    <div class=row>
        <div class="col-md-8">
            {% thumbnail object.image "800x600" crop="center" as im %}
                <img class="img-fluid" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
            {% endthumbnail %}
        </div>

        <div class="col-md-4">
            <div class="bg-light border p-3">
                <h3>Purchase Prints</h3>
                
                <form method="POST" action="{% url 'Gallery:AddPrintsToCart' %}">
                    {% csrf_token %}
                    <input type="hidden" name="Pictures" value='{{ object.pk }}' />
                    {% for pricePoint in object.gallery.price_points.all %}
                        <div class="form-group form-check">
                            <input type="checkbox" class="form-check-input" id="PriceOptions{{pricePoint.pk}}" name="PriceOptions" value="{{pricePoint.pk}}">
                            <label class="form-check-label" for="PriceOptions{{pricePoint.pk}}">{{ pricePoint.name }} - {{ pricePoint.price }}</label>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">Add To Cart</button>
                </form>
                    
            </div>
        </div>
    </div>
{% endblock container %}
    

Gallery/templates/Gallery/pictures_by_gallery_list.html
{% extends 'base.html' %}

{% block extra_head %}
    {{ block.super }}
{% endblock extra_head %}

{% block container %}
    <div class="breadcrumbs">
        / Event: <a href="/gallery/event/{{ gallery.event.pk }}">{{ gallery.event.name }}</a> / 
        Client: <a href="/gallery/client/{{ gallery.client.pk }}">{{ gallery.client.name }}</a> /
    </div>

    <h3 style="margin-top: 15px">{{ gallery.name }}</h3>
    
    <div class="row">
        {% for item in object_list %}
            <div class="col-12 col-md-6 col-lg-4 col-xl-3" onclick="window.location = '/gallery/picture/{{ item.id }}'">
                <div class="gallery-list-item" style="background-image:url('/media/{{ item.image }}');">
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock container %}
    

Site/templates/Site/about.html
{% extends 'base.html' %}
{% load static %}


{% block container %}
    <img class="img img-responsive" src="{% static '/Site/about.jpeg' %}"/>
    <p>Meet the photographer, Shannon Lee.

        With nearly ten years of experience with animals, I’ve worked hard to build a stunning collection of photos that capture everything you love about your little angel! I can’t wait to get to know everything you love and cherish about your own loving pet. I use my experience with animals to help me connect with them, giving them a comfortable environment to be in. At the end of the day, I’m in it for the animals.
        
        Past employee of Creature Comforts Pet Resort, and currently working at the Dunkirk PetsMart, I spend most of my time surrounded by animals. I’ve worked with over a thousand different pets and with each pet I meet I learn more about how every single one has its own personality and charm. I strive to bring out what makes your pet so special in each of my pictures.
        
        I can’t wait to meet your bundle(s) of love and help create lasting memories.</p>
{% endblock container %}
    

Site/templates/Site/cart.html
{% extends 'base.html' %}
{% load static %}


{% block container %}
    <div class="row">
        <div class="col-md-8">
            <table class="table">
                <thead>
                    <tr>
                        <th>Item</th>
                        <th>Price</th>
                        <th>Tax</th>
                        <th>Total</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in object_list %}
                        <tr>
                            <td>{{ item.category_content_object }}: Photo #{{ item.item_content_object.pk }}</td>
                            <td>{{ item.price }}</td>
                            <td>{{ item.tax }}</td>
                            <td>{{ item.total }}</td>
                            <td><button class="btn btn-danger">Remove</button></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-md-3">
            <div class="bg-light border">
                <h3>Cart Summery</h3>
                
            </div>
        </div>
    </div>
{% endblock container %}
    

Site/templates/Site/home.html
{% extends 'base.html' %}
{% load static %}


{% block extra_head %}
    {{ block.super }}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'Site/home.css' %}">
{% endblock extra_head %}
    


{% block body %}
    <!-- Carousel -->
    <div class="container-fluid p-0">
        <div id="homePageCarousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                {% for item in carousel %}
                    <li data-target="#homePageCarousel" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></li>
                {% endfor %}
            </ol>
            <div class="carousel-inner" style="max-width:100vw; height:92vh !important;">
                {% for item in carousel %}
                    <div class="carousel-item {% if forloop.first %}active{% endif %}">
                        <img class="d-block w-100" src="/media/{{ item.image }}" alt="{{ item.alt }}">
                        <div class="carousel-caption d-none d-md-block">
                            <h1>{{ item.caption }}</h1>
                            <a class="btn btn-primary" href="{{ item.button_url }}">{{ item.button_label }}</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#homePageCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#homePageCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>

    <!-- Service Cards -->
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card home-card">
                    <i class="fa fa-camera"></i>
                    <h5>PROFESSIONAL PHOTOGRAPHY</h5>
                    <p>Stunning photos that leave you with lasting memories. For a place on your wall and a place in your heart.</p>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card home-card">
                    <i class="fa fa-magic"></i>
                    <h5>WARDROBE INCLUDED</h5>
                    <p>Choose from our selection of adorable bandanas and other accessories to make your sweetheart look even more adorable.</p>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card home-card">
                    <i class="fa fa-heart"></i>
                    <h5>AWWS GUARANTEED</h5>
                    <p>Love your pictures, or we'll keep trying until you do! Smile and say "Aww"!</p>
                </div>
            </div>
        </div>
    </div>

    <!-- Find gallery form -->
    <div class="container" style="margin-top:15px;">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Find your Galleries</h5>
                <h6 class="card-subtitle mb-2 text-muted">Enter your email below to find any galleries associated with it.</h6>
                <form class="form-inline" method="GET" action="/gallery/email/">
                    <div class="form-group mb-2">
                        <label for="EmailSearch" class="">Email</label>
                    </div>
                    <div class="form-group mx-sm-3 mb-2">
                        <input type="email" name="email" class="form-control" id="EmailSearch" placeholder="Email">
                    </div>
                    <button type="submit" class="btn btn-primary mb-2">Search</button>
                </form>
                <small id="EmailSearch" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
        </div>
    </div>
{% endblock body %}
    

Site/templates/Site/price.html
{% extends 'base.html' %}


{% block container %}
    <h3>Print Prices</h3>
    <table class="table">
        <thead>
            <tr>
                <th>Item</th>
                <th>Print Type</th>
                <th>Print Size</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            {% for price in object_list %}
                <tr>
                    <td>{{ price.name }}</td>
                    <td>{{ price.get_print_type_display }}</td>
                    <td>{{ price.get_print_size_display }}</td>
                    <td>{{ price.formatted_price }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock container %}
    

Site/templates/Site/sessions.html
{% extends 'base.html' %}


{% block container %}
    <p>Lets get together! I am very flexible with where I am willing to meet you. From your homes, to parks and beaches, I’m willing to meet you anywhere.</p>

    <h5>Sessions will be priced as the following:</h5>
    
    <ul>
        <li>1 hour fee: $100</li>
        <li>15 minutes after 1st hour: $25</li>
        <li>Costume rental: $10</li>
    </ul>

    <p>I prefer to schedule two sessions in advance as well as one (free) 15 minute meet-and-greet before a session. Having the two covers if we get bad weather for outdoor shoots, sick animals, other conflicts, or if you are unsatisfied with the pictures taken. Any session not use will not be billed. You can decide to rent a costume at the shoot. I have several bandanas, and other such sweaters, or collar pieces to make your cutie even cuter. You may pick from as many costumes as you like. Some costumes may not be available in your sweetheart’s size. Price covers as many or as few costume pieces you would like to use. </p>

    <p>
        My name is Shannon, contact me here:<br/>
        Email: <a href="mailto:Shannon@pawsandawws.photography">Shannon@pawsandawws.photography</a><br/>
        Phone: <a href="tel:7164019360">(716) 401-9360</a><br/>
    </p>
{% endblock container %}
    

Site/templates/base.html
{% load static raven %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    {% block extra_head %}
        <link rel="stylesheet" href="{% static 'Site/base.css' %}">
    {% endblock extra_head %}
        

    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% block raw_body %}
        <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/">Paws and Awws Photography</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false">
                            Events
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for event in EVENTS %}
                                <a class="dropdown-item" href="/gallery/event/{{ event.pk }}">{{ event.name }}</a>
                            {% endfor %}                                
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/about/">The Photographer</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/session-info/">Session Info</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/prints/">Prints</a>
                    </li>
                </ul>
            </div>
        </nav>

        {% block body %}
            <div id="body-container" class="container">
                {% block container %}{% endblock container %}      
            </div>
        {% endblock body %}

        <footer>
            <div class="container">
                &COPY; Shannon Lee {% now "Y" %}
            </div>
        </footer>
    {% endblock raw_body %}

    
    {% block scripts %}
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script>Raven.config("{% sentry_public_dsn 'https' %}").install()</script>

    {% endblock scripts %}
  </body>
</html>